version: '3.7'

#################### THIS SECTIONS CONTAINS SOME EXPLANATIONS AND TIPS ON HOW TO WORK WITH DOCKER-COMPOSE ##############

# The password required to access our services are specified inside a .env file in the repository root directory. The env structure is documented in the .env.template file.

# The "ports" mapping exposes the given ports to the HOST. The "expose" mapping only exposes given the ports to other services, which is what we want because only the server talks to the external world

# To get an interactive shell inside a RUNNING container, use:
# 'docker-compose exec <service-mapping-key> <shell-command>'

########################################################################################################################

services:
  db:
    image: "postgres"
    build:
      context: ./db
    restart: always
    volumes:
      - ./db-data/:/db/postgres-init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sita
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  app-user:
    build: 
      context: ./serviceUser
    restart: always
    ports:
      - "9000:8080"
    environment:
     SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sita
     SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
     SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
     SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
     - db

  app-mdm:
    build: 
      context: ./serviceMDM
    restart: always
    ports:
      - "9001:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sita
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
     - db

  app-kpi:
    build: 
      context: ./serviceKPI
    restart: always
    ports:
      - "9002:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sita
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
     - db